### ISSUE TITLE
Error Message in Windows with Python 2.7

### ISSUE THREAD

**Issue by arksarks** [edouardswiac/python-edgar#1]
Getting Error Message

[Error 2] No such file or directory: "tmp/edgar.daily-index.master.20140417.idx"

**Comment by edouardswiac** [comment]
Since you are on Windows I would suggest using `edgar.download_all(ftp, "C:/Users/ark")` and see if the script downloads the files there. I doubt that `/tmp` is a valid path on a Windows system, hence it cannot be found when you glob on it.

**Comment by arksarks** [comment]
Thanks for the replay. I tried but still get error message with

[Error 2] No such file or directory: "C:/Users/ark/edgar.daily-index.master.20140417.idx"

I think something wrong with creating the temporary file and read from it.

**Comment by edouardswiac** [comment]
I don't have access to a windows machine right now. Can you try to use a virtual machine w/ a Linux instance?

**Comment by arksarks** [comment]
ok. let me try.
