### ISSUE TITLE
retrieve daily updates

### ISSUE THREAD

**Issue by noam2** [edouardswiac/python-edgar#13]
**Is your feature request related to a problem? Please describe.**
Would like to be able to get only new filings without retrieving the old ones

**Describe the solution you'd like**
Would like to be able to get only new filings without retrieving the old ones

**Comment by edouardswiac** [comment]
Hi
This is already implemented in https://github.com/edouardswiac/python-edgar/pull/11 but feel free to open a pull request if it needs improvements.
