### ISSUE TITLE
HTTPError: Forbidden

### ISSUE THREAD

**Issue by LaVespaGuido** [edouardswiac/python-edgar#23]
Hello!
I'm not expert, so I hope I'll be clear.

With "edgar.download_index" method, the following error returns:
HTTPError: Forbidden

I can reproduce the error even just by running the code shown in the "Common issues" paragraph of the documentation (adding the user_agent)
`
def main(): 
    import edgar
    user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.51'
    edgar.download_index(".", 2015, user_agent, skip_all_present_except_last=False)    
if __name__ == '__main__':
    main()  
`

I obtain this
![Capture](https://user-images.githubusercontent.com/90114644/132108684-229ec234-c427-410d-ba0a-bf6937b90273.JPG)

I used an older version, which started to give some issues, as missing quarters, and so on.
I updated to the latest version, and this is what's happening.
Also updated requests, but still "erroring".

**Desktop (please complete the following information):**
 - OS: Win 10
 - Python 3.7.11 (the screenshot is with 3.7.3, but with the .11 is the same)

In any way:
thank you for the support, but first, thank you for the package.

**Comment by LaVespaGuido** [comment]
Found out that the user-agent I were using, even if correct for the browser, was the problem.
Using 'XYZ/3.0' seems works fine!

**Comment by RainmakerP** [comment]
This trick worked nicely for a few days.

But it's back again, and the trick is not working anymore.

Can someone please help?
