### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by RainmakerP** [edouardswiac/python-edgar#24]
Hello,

My user agent is: 

`user_agent = "FTC edward@ftc.com"`

and the download command is 

`edgar.download_index(path, 2021, user_agent, skip_all_present_except_last=False)`

This is in accordance with the SEC's new fair usage standards.

Yet, we've started to receive the following error:

urllib.error.HTTPError: HTTP Error 403: Forbidden

![image](https://user-images.githubusercontent.com/76035250/135598197-515cf2be-f247-4c04-8f5e-60a193af817f.png)

Please help.

Thanks!

**Comment by AbderrahimBenJazia** [comment]
I have the same problem as you. Any help !

**Comment by svendaj** [comment]
I was not able to replicate your issue. Today I have installed latest version, set your `user_agent` and all four 2021 indexes were downloaded without any error in about 11 seconds.

**Comment by edouardswiac** [comment]
Thanks for confirming it's a client side issue @svendaj

**Comment by RainmakerP** [comment]
The issues appears for a few days and vanishes again, intermittenly.

It went away on it's own and has reappeared.
