### ISSUE TITLE
Asking about features this offers vs other Edgar tools

### ISSUE THREAD

**Issue by datatalking** [edouardswiac/python-edgar#28]
I'm new to Edgar filings so I'm trying to understand the difference between 
[edgarminers/python-edgar](https://github.com/edgarminers/python-edgar) updated 3 months ago, 265 stars, 24 waters, 62 forks

[sec-edgar-downloader](https://github.com/jadchaar/sec-edgar-downloader) updated 5 months ago, 265 stars, 11 Watchers, 75 Forks

[pyedgar](https://github.com/gaulinmp/pyedgar) updated 8 months ago 27 stars, 3 Watchers, 11 Forks

Should they work together or are they similar competitors but sibling rivals ?
There are other EDGAR tools and I'm trying to understand how to evaluate them

**Describe the solution you'd like**
I was looking for a single solution that also worked with pandas, perhaps a scraper, that saves to a database but i'm again still researching edgar and that data impacting my models. I work with a ton of data right now at about 17 tb domestically so I would be a heavy user and would like to contribute if its a fit.

Some of them have search functions others do not
Search by [stock ticker](https://en.wikipedia.org/wiki/Ticker_symbol)
Search by [Central Index Key (CIK)](https://en.wikipedia.org/wiki/Central_Index_Key)

No Search by SEC CIK [SEC CIK lookup tool](https://www.sec.gov/edgar/searchedgar/cik.htm) if you cannot find an appropriate ticker

Search for 351 filings - [list here](https://github.com/jadchaar/sec-edgar-downloader)

**Describe alternatives you've considered**
Rolled my own based off what I found online but your script would solve some issues.

**Additional context**
Pandas integration, database advice

**Comment by edouardswiac** [comment]
`sec-edgar-downloader` downloads any form given the CIK or ticker

`python-edgar` downloads the entire index of all submissions URLs for all CIKs. Up to you to filter the CIKs you want and download the submissions that you need.

Hope that helps.
