### ISSUE TITLE
Some files fail to download due to encoding errors under python3

### ISSUE THREAD

**Issue by RatkoJ** [edouardswiac/python-edgar#3]
I've noticed that specifically 2011-QTR4.tsv and 2017-QTR3.tsv end up having zero byte size after downloading using python3. I've looked through the code and traced this down to encoding error since apparently these files contain something that doesn't fit in utf-8. Running in python2 works fine because apparently it swept some errors under the carpet, which python3 doesn't anymore.

There is a good description here of what changed between python versions:
[](http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html)

I've managed to fix it by changing to latin-1, which behaves like python2. Not sure if this is the desired behavior though because errors are ignored and data may be corrupted.
`lines = str(lines, "latin-1")`

**Comment by edouardswiac** [comment]
Thanks for reporting the issue. I've never really looked at edgar files encoding, maybe it's all iso/latin and not utf8. I'll work on a fix, or you can submit a PR if you figure it out.

Is it failing for every ticker or only some? How can I reproduce?

**Comment by RatkoJ** [comment]
I never tried to look into which line of the index file was causing an issue.
But as I mentioned above, I've managed to fix it by replacing `lines = str(lines, "utf-8")` with `lines = str(lines, "latin-1")` in main.py.

**Comment by edouardswiac** [comment]
fixed in https://github.com/edouardswiac/python-edgar/pull/5
