### ISSUE TITLE
Documentation updation

### ISSUE THREAD

**Issue by Gaurang105** [edouardswiac/python-edgar#31]
While calling the python-edgar module, we'll get a destination error. 

Before:
edgar.download_index(download_directory, since_year, user_agent, skip_all_present_except_last=False)

After:
edgar.download_index(dest, since_year, user_agent, skip_all_present_except_last=False)

It should be like this.

**Comment by edouardswiac** [comment]
Thanks for the report 🙏 Can you submit a PR?

**Comment by Gaurang105** [comment]
Sure. I'll send a PR

**Comment by edouardswiac** [comment]
Fixed in https://github.com/edgarminers/python-edgar/pull/32
