### ISSUE TITLE
Oops! We can't find this file

### ISSUE THREAD

**Issue by gitsnippet** [edouardswiac/python-edgar#6]
Please to input `https://www.sec.gov/Archives/` in your browser,。

Oops! We can't find this file！

It seems like that SEC change  web diretroy in sec.gov.
How can use your  python-edgar ?

**Comment by edouardswiac** [comment]
Hey @gitsnippet.
You need to provide the full url to the archive, like https://www.sec.gov/Archives/edgar/full-index/2017/QTR3/master.zip . There is nothing per se at https://www.sec.gov/Archives/ .
