### ISSUE TITLE
fail to write to ASCII file due to encoding problem

### ISSUE THREAD

**Issue by yenchiayi** [edouardswiac/python-edgar#7]
I found that the downloaded "2011-QTR4.tsv" and "2017-QTR3.tsv" are empty inside. This seems to be related to issue #3 , while the solution in #3 simply ignored the error instead of fixing it thoroughly. After checking with the source code, I found the problem again comes from the encoding problem, as shown in the below picture. 
![image](https://user-images.githubusercontent.com/6258851/55427623-ac3aee80-5587-11e9-88f5-88641b1f3c49.png)

Since the error message pops up if we write to ASCII file, I tried to fix it by explicitly indicating that I want to write to UTF8 file, as shown in this stackoverflow page (https://stackoverflow.com/questions/934160/write-to-utf-8-file-in-python). And it works! Specifically, I replace `with open(dest+dest_name, 'w+') as idxfile:` with `with codecs.open(dest+dest_name, 'w+', 'utf-8') as idxfile`. I will submit a pull request for this later if you don't mind. Thanks.

**Comment by edouardswiac** [comment]
Thanks! I'll merge and cut a new release.

**Comment by edouardswiac** [comment]
Fixed in 2.6.1. Thanks!
